import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header/Header";
import Footer from "./Footer";
import { AuthProvider } from "../context/AuthProvider";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sri Handloom",
  description: "Generated by Sri Handloom",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <Header />

          <main className="flex-1">{children}</main>

          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${inter.variable} h-full antialiased`}>
//       <body className="min-h-full flex flex-col" suppressHydrationWarning={true}>
//         <AuthProvider>
//           <Header />
//           {children}
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
